name = "kylewhnewsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"
database_id = "57ac447b-ad2f-4477-9705-8033b20b4693"
